http-listen:
  call-collector: call-collector:50010
  rest-server: rest-server:50020
redpanda:
  brokers:
    - redpanda:9092
  topics:
    calls: parsed-json
    failed: failed
clickhouse:
  hosts:
    - clickhouse-server:9000
  database: history
  user: default
  password:
log:
  out: console                  # directory or `console` for stdout output
  age: 1                        # days
  size: 100                     # megabytes
  level: info