FROM golang:1.18-alpine

ENV LIBRD_VER=1.9.1
RUN apk add alpine-sdk bash git pkgconfig
RUN wget https://github.com/edenhill/librdkafka/archive/v${LIBRD_VER}.tar.gz && \
    tar -xvf v${LIBRD_VER}.tar.gz && \
    cd librdkafka-${LIBRD_VER} && \
    ./configure && \
    make && \
    make install

WORKDIR /app
COPY . .
RUN go mod download && \
    CGO_ENABLED=1 go build -tags musl,dynamic -o call-collector ./cmd/call-collector

CMD [ "/app/call-collector" ]