name: CI
on:
  push:
  pull_request:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - uses: actions/checkout@v3
      - name: Verify dependencies
        run: go mod verify
      - name: Linter
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: -p format,import,module
      - name: Build
        run: go build cmd
      - name: golangci-lint