name: 'Project checker'
on: push

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Verify dependencies
        run: go mod verify
      - name: Linter
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: -p format,import,module
      - name: Build
        run: go build cmd